version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db_agence
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - odoo-net

  odoo:
    image: odoo:17
    container_name: odoo_agence
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=postgres
    volumes:
      - ./extra-addons:/mnt/extra-addons
    networks:
      - odoo-net

networks:
  odoo-net:

volumes:
  db_data:
